server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs

spring:
  application:
    name: payment-management
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG